/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.korfinancial.streaming.kopper.cast.registry.kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UpcasterChainNodeState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7432820300597217937L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UpcasterChainNodeState\",\"namespace\":\"com.korfinancial.streaming.kopper.cast.registry.kafka\",\"fields\":[{\"name\":\"subject\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"expressions\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UpcasterChainNodeState> ENCODER =
      new BinaryMessageEncoder<UpcasterChainNodeState>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UpcasterChainNodeState> DECODER =
      new BinaryMessageDecoder<UpcasterChainNodeState>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UpcasterChainNodeState> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UpcasterChainNodeState> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UpcasterChainNodeState> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UpcasterChainNodeState>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UpcasterChainNodeState to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UpcasterChainNodeState from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UpcasterChainNodeState instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UpcasterChainNodeState fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String subject;
  private int version;
  private java.util.Map<java.lang.String,java.lang.String> expressions;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UpcasterChainNodeState() {}

  /**
   * All-args constructor.
   * @param subject The new value for subject
   * @param version The new value for version
   * @param expressions The new value for expressions
   */
  public UpcasterChainNodeState(java.lang.String subject, java.lang.Integer version, java.util.Map<java.lang.String,java.lang.String> expressions) {
    this.subject = subject;
    this.version = version;
    this.expressions = expressions;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return subject;
    case 1: return version;
    case 2: return expressions;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: subject = value$ != null ? value$.toString() : null; break;
    case 1: version = (java.lang.Integer)value$; break;
    case 2: expressions = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'subject' field.
   * @return The value of the 'subject' field.
   */
  public java.lang.String getSubject() {
    return subject;
  }


  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.String value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public int getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'expressions' field.
   * @return The value of the 'expressions' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getExpressions() {
    return expressions;
  }


  /**
   * Sets the value of the 'expressions' field.
   * @param value the value to set.
   */
  public void setExpressions(java.util.Map<java.lang.String,java.lang.String> value) {
    this.expressions = value;
  }

  /**
   * Creates a new UpcasterChainNodeState RecordBuilder.
   * @return A new UpcasterChainNodeState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder newBuilder() {
    return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder();
  }

  /**
   * Creates a new UpcasterChainNodeState RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UpcasterChainNodeState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder newBuilder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder other) {
    if (other == null) {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder();
    } else {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder(other);
    }
  }

  /**
   * Creates a new UpcasterChainNodeState RecordBuilder by copying an existing UpcasterChainNodeState instance.
   * @param other The existing instance to copy.
   * @return A new UpcasterChainNodeState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder newBuilder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState other) {
    if (other == null) {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder();
    } else {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder(other);
    }
  }

  /**
   * RecordBuilder for UpcasterChainNodeState instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UpcasterChainNodeState>
    implements org.apache.avro.data.RecordBuilder<UpcasterChainNodeState> {

    private java.lang.String subject;
    private int version;
    private java.util.Map<java.lang.String,java.lang.String> expressions;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.version)) {
        this.version = data().deepCopy(fields()[1].schema(), other.version);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.expressions)) {
        this.expressions = data().deepCopy(fields()[2].schema(), other.expressions);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UpcasterChainNodeState instance
     * @param other The existing instance to copy.
     */
    private Builder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.version)) {
        this.version = data().deepCopy(fields()[1].schema(), other.version);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expressions)) {
        this.expressions = data().deepCopy(fields()[2].schema(), other.expressions);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.String getSubject() {
      return subject;
    }


    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder setSubject(java.lang.String value) {
      validate(fields()[0], value);
      this.subject = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public int getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder setVersion(int value) {
      validate(fields()[1], value);
      this.version = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder clearVersion() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'expressions' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getExpressions() {
      return expressions;
    }


    /**
      * Sets the value of the 'expressions' field.
      * @param value The value of 'expressions'.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder setExpressions(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[2], value);
      this.expressions = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'expressions' field has been set.
      * @return True if the 'expressions' field has been set, false otherwise.
      */
    public boolean hasExpressions() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'expressions' field.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState.Builder clearExpressions() {
      expressions = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UpcasterChainNodeState build() {
      try {
        UpcasterChainNodeState record = new UpcasterChainNodeState();
        record.subject = fieldSetFlags()[0] ? this.subject : (java.lang.String) defaultValue(fields()[0]);
        record.version = fieldSetFlags()[1] ? this.version : (java.lang.Integer) defaultValue(fields()[1]);
        record.expressions = fieldSetFlags()[2] ? this.expressions : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UpcasterChainNodeState>
    WRITER$ = (org.apache.avro.io.DatumWriter<UpcasterChainNodeState>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UpcasterChainNodeState>
    READER$ = (org.apache.avro.io.DatumReader<UpcasterChainNodeState>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.subject);

    out.writeInt(this.version);

    long size0 = this.expressions.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> e0: this.expressions.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.String v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.subject = in.readString();

      this.version = in.readInt();

      long size0 = in.readMapStart();
      java.util.Map<java.lang.String,java.lang.String> m0 = this.expressions; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)size0);
        this.expressions = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String k0 = null;
          k0 = in.readString();
          java.lang.String v0 = null;
          v0 = in.readString();
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.subject = in.readString();
          break;

        case 1:
          this.version = in.readInt();
          break;

        case 2:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.String,java.lang.String> m0 = this.expressions; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)size0);
            this.expressions = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String k0 = null;
              k0 = in.readString();
              java.lang.String v0 = null;
              v0 = in.readString();
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










