/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.korfinancial.streaming.kopper.cast.registry.kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UpcasterChainState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8679659250724427487L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UpcasterChainState\",\"namespace\":\"com.korfinancial.streaming.kopper.cast.registry.kafka\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nodes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"UpcasterChainNodeState\",\"fields\":[{\"name\":\"subject\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"expressions\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UpcasterChainState> ENCODER =
      new BinaryMessageEncoder<UpcasterChainState>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UpcasterChainState> DECODER =
      new BinaryMessageDecoder<UpcasterChainState>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UpcasterChainState> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UpcasterChainState> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UpcasterChainState> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UpcasterChainState>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UpcasterChainState to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UpcasterChainState from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UpcasterChainState instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UpcasterChainState fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> nodes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UpcasterChainState() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param nodes The new value for nodes
   */
  public UpcasterChainState(java.lang.String id, java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> nodes) {
    this.id = id;
    this.nodes = nodes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return nodes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: nodes = (java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'nodes' field.
   * @return The value of the 'nodes' field.
   */
  public java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> getNodes() {
    return nodes;
  }


  /**
   * Sets the value of the 'nodes' field.
   * @param value the value to set.
   */
  public void setNodes(java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> value) {
    this.nodes = value;
  }

  /**
   * Creates a new UpcasterChainState RecordBuilder.
   * @return A new UpcasterChainState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder newBuilder() {
    return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder();
  }

  /**
   * Creates a new UpcasterChainState RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UpcasterChainState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder newBuilder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder other) {
    if (other == null) {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder();
    } else {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder(other);
    }
  }

  /**
   * Creates a new UpcasterChainState RecordBuilder by copying an existing UpcasterChainState instance.
   * @param other The existing instance to copy.
   * @return A new UpcasterChainState RecordBuilder
   */
  public static com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder newBuilder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState other) {
    if (other == null) {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder();
    } else {
      return new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder(other);
    }
  }

  /**
   * RecordBuilder for UpcasterChainState instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UpcasterChainState>
    implements org.apache.avro.data.RecordBuilder<UpcasterChainState> {

    private java.lang.String id;
    private java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> nodes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nodes)) {
        this.nodes = data().deepCopy(fields()[1].schema(), other.nodes);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UpcasterChainState instance
     * @param other The existing instance to copy.
     */
    private Builder(com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nodes)) {
        this.nodes = data().deepCopy(fields()[1].schema(), other.nodes);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nodes' field.
      * @return The value.
      */
    public java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> getNodes() {
      return nodes;
    }


    /**
      * Sets the value of the 'nodes' field.
      * @param value The value of 'nodes'.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder setNodes(java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> value) {
      validate(fields()[1], value);
      this.nodes = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nodes' field has been set.
      * @return True if the 'nodes' field has been set, false otherwise.
      */
    public boolean hasNodes() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nodes' field.
      * @return This builder.
      */
    public com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainState.Builder clearNodes() {
      nodes = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UpcasterChainState build() {
      try {
        UpcasterChainState record = new UpcasterChainState();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.nodes = fieldSetFlags()[1] ? this.nodes : (java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UpcasterChainState>
    WRITER$ = (org.apache.avro.io.DatumWriter<UpcasterChainState>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UpcasterChainState>
    READER$ = (org.apache.avro.io.DatumReader<UpcasterChainState>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    long size0 = this.nodes.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState e0: this.nodes) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> a0 = this.nodes;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>((int)size0, SCHEMA$.getField("nodes").schema());
        this.nodes = a0;
      } else a0.clear();
      SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> a0 = this.nodes;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>((int)size0, SCHEMA$.getField("nodes").schema());
            this.nodes = a0;
          } else a0.clear();
          SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.korfinancial.streaming.kopper.cast.registry.kafka.UpcasterChainNodeState();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










